matrix:
  include:
    - language: node_js
      node_js: '10'
      env:
        global:
          - NODE_OPTIONS=--max_old_space_size=4096
      before_script:
        - ./build-script.sh
      # install: yarn --frozen-lockfile --non-interactive || (echo 'package.json is not in sync with yarn.lock, check that you include yarn.lock' && false)
      script:
        - yarn prettier --list-different &&
          yarn build:dev &&
          yarn test --forceExit --maxWorkers=4
    - language: go
      go: 1.9.4
      before_script:
        - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
      install:
        - pwd
        - make dep-install
        - make swagger-install
        - make gometalinter-install
#        - make dep-update
      script:
        - if [ ! -z "$(gofmt -l ${GO_FILES})" ]; then echo "These files need to be formatted:" "$(gofmt -l ${GO_FILES})";echo "Diff files:"; gofmt -d ${GO_FILES}; exit 1; fi # Gofmt Linter
#        - make lint
        - make clean build test-race
        - make swagger-travis
        - make build
        - make docker-build
after_success:
- echo kiali-pass